name: pocket_functions
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.2
  args: ^2.5.0
  yaml_writer: ^2.0.0
  http: ^1.2.2
  build: ^2.0.0
  source_gen: ^1.0.0
  analyzer: ^5.0.0
  archive: ^3.3.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

executables:
  pocket_functions: pocket_functions
